In [1]:
import pandas as pd
import os
import numpy as np
import datetime as dt

In [2]:
df = pd.read_excel(r"C:\Users\Raffaele.Sportiello\OneDrive - Wolters Kluwer\Documents\Dashboard rinnovi\20220310_dati dash_diretta_01.03.2022_FEBBRAIO22.xlsx")

In [3]:
df

,Tipo Partner Agg,Sales Director,Agente,Cod. Agente,RSM Agente Descr.,New Current State,New Delta Type,Cliente FATTURA,Numero Contratto,Sistema,NumSist - Stato Kontratto,NumSist - Data Disattivazione Lic,#Contracts,Opening 2022,Landing 2022_2,Landing 2022_3,Delta YTD,Delta MoM,Actual,pV_BASELINE N
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21019,37148009.90,37077273.90,36890270.01,-2.577399e+05,-187003.89,29167179.50,38496648.86
1,Diretto,WKIC NORD OVEST,LUCERTONI MASSIMO,K170,NORD OVEST,01.Attivo,Mantenuto,66191.0,142,SISTCONT,NaN,0.0,1,5561.50,5561.50,5561.50,-9.094947e-13,0.00,5561.50,5561.50
2,Diretto,WKIC NORD OVEST,LUCERTONI MASSIMO,K170,NORD OVEST,01.Attivo,Mantenuto,118156.0,246,SISTCONT,NaN,0.0,1,16172.50,16172.50,16172.50,0.000000e+00,0.00,16172.50,16492.50
3,Diretto,WKIC NORD OVEST,LUCERTONI MASSIMO,K170,NORD OVEST,01.Attivo,Mantenuto,461608.0,287,SISTCONT,NaN,0.0,1,6450.00,6450.00,6450.00,-1.818989e-12,0.00,6450.00,6450.00
4,Diretto,WKIC NORD OVEST,LUCERTONI MASSIMO,K170,NORD OVEST,01.Attivo,Mantenuto,559249.0,295,SISTCONT,NaN,0.0,1,9249.50,9249.50,9249.50,0.000000e+00,0.00,9249.50,9249.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21015,Diretto,WKIC NORD EST,GAVASSO NAZZARENA,K124,NORD EST,01.Attivo,Mantenuto,1066610.0,V3954,TUTTOTEL,NaN,0.0,1,800.00,800.00,800.00,-1.136868e-13,0.00,800.00,800.00
21016,Diretto,WKIC NORD EST,CALGARO PAOLA,K005,NORD EST,01.Attivo,Mantenuto,421578.0,V3957,TUTTOTEL,NaN,0.0,1,532.84,532.84,532.84,0.000000e+00,0.00,532.84,532.84
21017,Diretto,WKIC NORD EST,METTE ILARIA,K175,NORD EST,01.Attivo,Mantenuto,1593109.0,V3998-S,TUTTOTEL,NaN,0.0,1,200.00,200.00,200.00,5.684342e-14,0.00,200.00,200.00
21018,Diretto,WKIC NORD EST,CARETTA BARBARA,K199,NORD EST,01.Attivo,Mantenuto,9815564.0,V3999-S,TUTTOTEL,NaN,0.0,1,203.00,203.00,203.00,5.684342e-14,0.00,203.00,203.00
21019,Diretto,WKIC NORD EST,CALGARO PAOLA,K005,NORD EST,01.Attivo,Mantenuto,2101248.0,V4019,WEBANYWHER,NaN,0.0,1,206.00,206.00,206.00,-2.842171e-14,0.00,206.00,206.00

In [20]:
df.iloc[1:,:].groupby(["New Current State", "New Delta Type"]).agg({"Opening 2022":"sum"}).unstack(level=0).fillna(0).style.format("{:,.0f}").background_gradient(axis=None, vmax=100000, vmin=1000)